name: Crawler

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Crawler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Crawl
        run: |
          npm ci
          npm run crawler
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          user_name: "JacobLinCool"
          user_email: "jacoblincool@users.noreply.github.com"
          publish_branch: "data"
          keep_files: true
